[env:waveshare43]
platform = https://github.com/pioarduino/platform-espressif32.git#develop

board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200

board_build.flash_mode = qio
board_build.flash_size = 16MB
board_build.psram_type = opi
board_build.arduino.memory_type = qio_opi

build_flags =
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DBOARD_WAVESHARE_ESP32_S3_TOUCH_LCD_4_3_B
    -DESP_PANEL_BOARD_DEFAULT_USE_SUPPORTED=1
    -std=gnu++20

lib_deps =
    https://github.com/esp-arduino-libs/ESP32_Display_Panel.git
    https://github.com/esp-arduino-libs/ESP32_IO_Expander.git
    https://github.com/esp-arduino-libs/esp-lib-utils.git